// Sentence-mode data for each verb.
// Each entry: [spanish_sentence_with_blank, english_translation]
// indicative[0-5]  → yo, tú, él/ella, nosotros, vosotros, ellos
// subjunctive[0-5] → same order, with a trigger clause
// imperative[0-4]  → tú, Ud., nosotros, vosotros, Uds.
// gerund / infinitive / past_participle → single [es, en] pair

const VERB_SENTENCES = {
    hablar: {
        indicative: [
            ["Yo ___ español con mi familia.", "I speak Spanish with my family."],
            ["Tú ___ muy bien el inglés.", "You speak English very well."],
            ["Ella ___ con su madre por teléfono.", "She speaks with her mother by phone."],
            ["Nosotros ___ sobre el proyecto.", "We speak about the project."],
            ["Vosotros ___ demasiado en clase.", "You all talk too much in class."],
            ["Ellos ___ tres idiomas.", "They speak three languages."],
        ],
        subjunctive: [
            ["Ojalá que yo ___ mejor en público.", "Hopefully I speak better in public."],
            ["Espero que tú ___ con el jefe.", "I hope you speak with the boss."],
            ["Es importante que ella ___ más despacio.", "It's important that she speak more slowly."],
            ["Ojalá que nosotros ___ más inglés.", "Hopefully we speak more English."],
            ["Necesito que vosotros ___ con respeto.", "I need you all to speak with respect."],
            ["Quiero que ellos ___ con claridad.", "I want them to speak clearly."],
        ],
        imperative: [
            ["___ más despacio, por favor.", "Speak more slowly, please."],
            ["___ con el director esta tarde.", "Speak with the director this afternoon."],
            ["___ en inglés hoy.", "Let's speak in English today."],
            ["___ en voz alta.", "Speak aloud."],
            ["___ con respeto en todo momento.", "Speak with respect at all times."],
        ],
        gerund: ["Estamos ___ sobre el viaje.", "We are talking about the trip."],
        infinitive: ["Es importante ___ bien.", "It is important to speak well."],
        past_participle: ["He ___ con el médico hoy.", "I have spoken with the doctor today."],
    },
    comer: {
        indicative: [
            ["Yo ___ en casa todos los días.", "I eat at home every day."],
            ["Tú ___ demasiada azúcar.", "You eat too much sugar."],
            ["Él ___ pizza los viernes.", "He eats pizza on Fridays."],
            ["Nosotros ___ juntos a las dos.", "We eat together at two."],
            ["Vosotros ___ en ese restaurante.", "You all eat at that restaurant."],
            ["Ellos ___ en la cafetería.", "They eat in the cafeteria."],
        ],
        subjunctive: [
            ["Ojalá que yo ___ más sano.", "Hopefully I eat healthier."],
            ["Quiero que tú ___ más verduras.", "I want you to eat more vegetables."],
            ["Espero que él ___ antes de salir.", "I hope he eats before leaving."],
            ["Es bueno que nosotros ___ juntos.", "It's good that we eat together."],
            ["Quiero que vosotros ___ bien.", "I want you all to eat well."],
            ["Espero que ellos ___ algo.", "I hope they eat something."],
        ],
        imperative: [
            ["___ toda la sopa.", "Eat all the soup."],
            ["___ algo antes de la reunión.", "Eat something before the meeting."],
            ["___ en ese restaurante esta noche.", "Let's eat at that restaurant tonight."],
            ["___ despacio y con calma.", "Eat slowly and calmly."],
            ["___ bien durante el viaje.", "Eat well during the trip."],
        ],
        gerund: ["Están ___ en la terraza.", "They are eating on the terrace."],
        infinitive: ["Hay que ___ sano.", "One must eat healthily."],
        past_participle: ["He ___ muy bien hoy.", "I have eaten very well today."],
    },
    vivir: {
        indicative: [
            ["Yo ___ en Madrid.", "I live in Madrid."],
            ["Tú ___ cerca del trabajo.", "You live near work."],
            ["Ella ___ en un piso pequeño.", "She lives in a small flat."],
            ["Nosotros ___ en el campo.", "We live in the countryside."],
            ["Vosotros ___ muy lejos de aquí.", "You all live very far from here."],
            ["Ellos ___ en el mismo barrio.", "They live in the same neighborhood."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más tranquilo.", "I want to live more peacefully."],
            ["Espero que tú ___ feliz siempre.", "I hope you always live happily."],
            ["Es importante que ella ___ cerca de sus hijos.", "It's important that she live near her children."],
            ["Ojalá que nosotros ___ en paz.", "Hopefully we live in peace."],
            ["Quiero que vosotros ___ bien.", "I want you all to live well."],
            ["Espero que ellos ___ en una casa grande.", "I hope they live in a big house."],
        ],
        imperative: [
            ["___ el momento.", "Live in the moment."],
            ["___ sin miedo.", "Live without fear."],
            ["___ cada día al máximo.", "Let's live every day to the fullest."],
            ["___ con alegría.", "Live with joy."],
            ["___ plenamente.", "Live fully."],
        ],
        gerund: ["Están ___ en un hotel por ahora.", "They are living in a hotel for now."],
        infinitive: ["Quiero ___ cerca del mar.", "I want to live near the sea."],
        past_participle: ["Hemos ___ aquí diez años.", "We have lived here for ten years."],
    },
    ser: {
        indicative: [
            ["Yo ___ estudiante de español.", "I am a student of Spanish."],
            ["Tú ___ muy inteligente.", "You are very intelligent."],
            ["Ella ___ profesora de música.", "She is a music teacher."],
            ["Nosotros ___ buenos amigos.", "We are good friends."],
            ["Vosotros ___ de Madrid.", "You all are from Madrid."],
            ["Ellos ___ hermanos.", "They are brothers."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejor persona.", "I want to be a better person."],
            ["Espero que tú ___ feliz.", "I hope you are happy."],
            ["Es importante que ella ___ honesta.", "It's important that she be honest."],
            ["Ojalá que nosotros ___ más unidos.", "Hopefully we are more united."],
            ["Quiero que vosotros ___ responsables.", "I want you all to be responsible."],
            ["Espero que ellos ___ puntuales.", "I hope they are punctual."],
        ],
        imperative: [
            ["___ amable con todos.", "Be kind to everyone."],
            ["___ paciente, por favor.", "Be patient, please."],
            ["___ más cuidadosos.", "Let's be more careful."],
            ["___ honestos con vosotros mismos.", "Be honest with yourselves."],
            ["___ respetuosos.", "Be respectful."],
        ],
        gerund: ["Está ___ muy generoso con todos.", "He is being very generous with everyone."],
        infinitive: ["No puede ___ así.", "It can't be like this."],
        past_participle: ["Ha ___ un día muy largo.", "It has been a very long day."],
    },
    ir: {
        indicative: [
            ["Yo ___ al trabajo en autobús.", "I go to work by bus."],
            ["Tú ___ al gimnasio cada mañana.", "You go to the gym every morning."],
            ["Ella ___ de compras los sábados.", "She goes shopping on Saturdays."],
            ["Nosotros ___ a la playa en verano.", "We go to the beach in summer."],
            ["Vosotros ___ al cine los viernes.", "You all go to the cinema on Fridays."],
            ["Ellos ___ a casa tarde.", "They go home late."],
        ],
        subjunctive: [
            ["Quiero que yo ___ al extranjero.", "I want to go abroad."],
            ["Espero que tú ___ al médico.", "I hope you go to the doctor."],
            ["Es importante que ella ___ al dentista.", "It's important that she go to the dentist."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we go together."],
            ["Quiero que vosotros ___ con cuidado.", "I want you all to go carefully."],
            ["Espero que ellos ___ a tiempo.", "I hope they go on time."],
        ],
        imperative: [
            ["___ a comprar el pan.", "Go buy the bread."],
            ["___ con calma.", "Go calmly."],
            ["___ al parque esta tarde.", "Let's go to the park this afternoon."],
            ["___ sin mí, yo os espero aquí.", "Go without me, I'll wait here."],
            ["___ por ese camino.", "Go along that path."],
        ],
        gerund: ["Estoy ___ al mercado ahora.", "I am going to the market now."],
        infinitive: ["Necesito ___ al banco.", "I need to go to the bank."],
        past_participle: ["Hemos ___ al museo esta mañana.", "We have gone to the museum this morning."],
    },
    hacer: {
        indicative: [
            ["Yo ___ los deberes por la tarde.", "I do homework in the afternoon."],
            ["Tú ___ mucho ejercicio.", "You do a lot of exercise."],
            ["Él ___ la cena para todos.", "He makes dinner for everyone."],
            ["Nosotros ___ un viaje cada verano.", "We take a trip every summer."],
            ["Vosotros ___ deporte juntos.", "You all play sports together."],
            ["Ellos ___ todo lo posible.", "They do everything possible."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más ejercicio.", "I want to do more exercise."],
            ["Espero que tú ___ los deberes.", "I hope you do your homework."],
            ["Es importante que ella ___ su trabajo bien.", "It's important that she do her work well."],
            ["Ojalá que nosotros ___ algo especial.", "Hopefully we do something special."],
            ["Quiero que vosotros ___ más esfuerzo.", "I want you all to make more effort."],
            ["Espero que ellos ___ lo correcto.", "I hope they do the right thing."],
        ],
        imperative: [
            ["___ la cama antes de salir.", "Make the bed before leaving."],
            ["___ el trabajo para mañana.", "Do the work for tomorrow."],
            ["___ una pausa de cinco minutos.", "Let's take a five-minute break."],
            ["___ los deberes esta tarde.", "Do your homework this afternoon."],
            ["___ todo lo posible.", "Do everything possible."],
        ],
        gerund: ["Está ___ la compra en el supermercado.", "She is doing the shopping at the supermarket."],
        infinitive: ["Hay que ___ ejercicio todos los días.", "One must exercise every day."],
        past_participle: ["He ___ la tarea ya.", "I have done the task already."],
    },
    tener: {
        indicative: [
            ["Yo ___ mucho trabajo esta semana.", "I have a lot of work this week."],
            ["Tú ___ dos hermanos.", "You have two brothers."],
            ["Él ___ un coche nuevo.", "He has a new car."],
            ["Nosotros ___ una reunión importante.", "We have an important meeting."],
            ["Vosotros ___ mucha suerte.", "You all have a lot of luck."],
            ["Ellos ___ una casa grande.", "They have a big house."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más tiempo libre.", "I want to have more free time."],
            ["Espero que tú ___ cuidado.", "I hope you are careful."],
            ["Es importante que ella ___ paciencia.", "It's important that she have patience."],
            ["Ojalá que nosotros ___ éxito.", "Hopefully we have success."],
            ["Quiero que vosotros ___ todo listo.", "I want you all to have everything ready."],
            ["Espero que ellos ___ lo que necesitan.", "I hope they have what they need."],
        ],
        imperative: [
            ["___ cuidado en la carretera.", "Be careful on the road."],
            ["___ paciencia, por favor.", "Be patient, please."],
            ["___ en cuenta todas las opciones.", "Let's take all options into account."],
            ["___ todo listo para las cinco.", "Have everything ready by five."],
            ["___ cuidado con el equipaje.", "Be careful with the luggage."],
        ],
        gerund: ["Está ___ problemas en el trabajo.", "She is having problems at work."],
        infinitive: ["No se puede ___ todo.", "One can't have everything."],
        past_participle: ["He ___ suerte hoy.", "I have been lucky today."],
    },
    estar: {
        indicative: [
            ["Yo ___ en casa todo el día.", "I am at home all day."],
            ["Tú ___ muy cansado hoy.", "You are very tired today."],
            ["Ella ___ en la oficina ahora.", "She is at the office now."],
            ["Nosotros ___ listos para salir.", "We are ready to leave."],
            ["Vosotros ___ de vacaciones.", "You all are on vacation."],
            ["Ellos ___ muy contentos.", "They are very happy."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más tranquilo.", "I want to be calmer."],
            ["Espero que tú ___ bien pronto.", "I hope you are well soon."],
            ["Es importante que ella ___ aquí.", "It's important that she be here."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we are together."],
            ["Quiero que vosotros ___ cómodos.", "I want you all to be comfortable."],
            ["Espero que ellos ___ listos.", "I hope they are ready."],
        ],
        imperative: [
            ["___ quieto y escucha.", "Be still and listen."],
            ["___ tranquilo, todo va bien.", "Be calm, everything is fine."],
            ["___ atentos durante la clase.", "Let's be attentive during class."],
            ["___ listos a las ocho.", "Be ready at eight."],
            ["___ preparados para mañana.", "Be prepared for tomorrow."],
        ],
        gerund: ["Sigo ___ en casa.", "I'm still staying at home."],
        infinitive: ["No quiero ___ solo.", "I don't want to be alone."],
        past_participle: ["Ha ___ enferma esta semana.", "She has been sick this week."],
    },
    decir: {
        indicative: [
            ["Yo ___ la verdad siempre.", "I always tell the truth."],
            ["Tú ___ cosas muy interesantes.", "You say very interesting things."],
            ["Él ___ que no puede venir.", "He says he can't come."],
            ["Nosotros ___ lo que pensamos.", "We say what we think."],
            ["Vosotros ___ tonterías a veces.", "You all say silly things sometimes."],
            ["Ellos ___ que el proyecto es difícil.", "They say the project is difficult."],
        ],
        subjunctive: [
            ["Quiero que yo ___ las cosas con más claridad.", "I want to say things more clearly."],
            ["Espero que tú ___ la verdad.", "I hope you tell the truth."],
            ["Es importante que ella ___ lo que siente.", "It's important that she say what she feels."],
            ["Ojalá que nosotros ___ las cosas correctas.", "Hopefully we say the right things."],
            ["Necesito que vosotros ___ lo que pasó.", "I need you all to say what happened."],
            ["Quiero que ellos ___ la verdad.", "I want them to tell the truth."],
        ],
        imperative: [
            ["___ la verdad.", "Tell the truth."],
            ["___ su nombre, por favor.", "Say your name, please."],
            ["___ lo que pensamos.", "Let's say what we think."],
            ["___ todo lo que sabéis.", "Say everything you know."],
            ["___ sus opiniones claramente.", "Say your opinions clearly."],
        ],
        gerund: ["Está ___ algo muy importante.", "He is saying something very important."],
        infinitive: ["No sé cómo ___ esto.", "I don't know how to say this."],
        past_participle: ["He ___ todo lo que sé.", "I have said everything I know."],
    },
    poder: {
        indicative: [
            ["Yo no ___ venir a la reunión.", "I can't come to the meeting."],
            ["Tú ___ hablar con él directamente.", "You can speak with him directly."],
            ["Ella ___ correr muy rápido.", "She can run very fast."],
            ["Nosotros ___ terminar el proyecto a tiempo.", "We can finish the project on time."],
            ["Vosotros ___ entrar ahora.", "You all can come in now."],
            ["Ellos ___ resolver el problema.", "They can solve the problem."],
        ],
        subjunctive: [
            ["Espero que yo ___ asistir.", "I hope I can attend."],
            ["Ojalá que tú ___ venir.", "Hopefully you can come."],
            ["Espero que ella ___ recuperarse pronto.", "I hope she can recover soon."],
            ["Ojalá que nosotros ___ terminar a tiempo.", "Hopefully we can finish on time."],
            ["Espero que vosotros ___ ayudarnos.", "I hope you all can help us."],
            ["Quiero que ellos ___ asistir.", "I want them to be able to attend."],
        ],
        imperative: [
            ["___ hacerlo mejor.", "You can do it better."],
            ["___ contar con nosotros.", "You can count on us."],
            ["___ hacerlo juntos.", "We can do it together."],
            ["___ mejorar si os esforzáis.", "You can improve if you make an effort."],
            ["___ lograrlo.", "You can achieve it."],
        ],
        gerund: ["Está ___ terminar el proyecto.", "She is able to finish the project."],
        infinitive: ["No voy a ___ ir.", "I'm not going to be able to go."],
        past_participle: ["No he ___ dormir bien.", "I haven't been able to sleep well."],
    },
    querer: {
        indicative: [
            ["Yo ___ aprender más idiomas.", "I want to learn more languages."],
            ["Tú ___ mucho a tu familia.", "You love your family very much."],
            ["Ella ___ ser médica.", "She wants to be a doctor."],
            ["Nosotros ___ ir al concierto.", "We want to go to the concert."],
            ["Vosotros ___ comer fuera esta noche.", "You all want to eat out tonight."],
            ["Ellos ___ comprar una casa nueva.", "They want to buy a new house."],
        ],
        subjunctive: [
            ["Ojalá que yo ___ volver algún día.", "Hopefully I want to return someday."],
            ["Espero que tú ___ ayudarme.", "I hope you want to help me."],
            ["Es bueno que ella ___ aprender.", "It's good that she wants to learn."],
            ["Ojalá que nosotros ___ lo mismo.", "Hopefully we want the same thing."],
            ["Espero que vosotros ___ participar.", "I hope you all want to participate."],
            ["Quiero que ellos ___ colaborar.", "I want them to want to collaborate."],
        ],
        imperative: [
            ["___ más a ti mismo.", "Love yourself more."],
            ["___ lo que tiene.", "Love what you have."],
            ["___ hacer las cosas bien.", "Let's want to do things well."],
            ["___ con todo el corazón.", "Love with all your heart."],
            ["___ aprender más.", "Want to learn more."],
        ],
        gerund: ["Está ___ comprar un coche nuevo.", "He is wanting to buy a new car."],
        infinitive: ["No sé qué ___ de la vida.", "I don't know what to want from life."],
        past_participle: ["He ___ decirte esto desde hace tiempo.", "I have wanted to tell you this for a long time."],
    },
    saber: {
        indicative: [
            ["Yo ___ hablar tres idiomas.", "I know how to speak three languages."],
            ["Tú ___ la respuesta.", "You know the answer."],
            ["Ella ___ cocinar muy bien.", "She knows how to cook very well."],
            ["Nosotros ___ dónde está el problema.", "We know where the problem is."],
            ["Vosotros ___ la verdad.", "You all know the truth."],
            ["Ellos ___ tocar la guitarra.", "They know how to play the guitar."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más sobre historia.", "I want to know more about history."],
            ["Espero que tú ___ lo que haces.", "I hope you know what you're doing."],
            ["Es importante que ella ___ la verdad.", "It's important that she know the truth."],
            ["Ojalá que nosotros ___ la respuesta.", "Hopefully we know the answer."],
            ["Necesito que vosotros ___ el protocolo.", "I need you all to know the protocol."],
            ["Quiero que ellos ___ lo que pasó.", "I want them to know what happened."],
        ],
        imperative: [
            ["___ que siempre te apoyo.", "Know that I always support you."],
            ["___ que tiene todo mi respeto.", "Know that you have all my respect."],
            ["___ que no estamos solos.", "Let's know we are not alone."],
            ["___ lo que hacéis.", "Know what you're doing."],
            ["___ que cuentan con nosotros.", "Know that they can count on us."],
        ],
        gerund: ["Está ___ manejar muy bien la situación.", "She is knowing how to handle the situation very well."],
        infinitive: ["Es bueno ___ varios idiomas.", "It's good to know several languages."],
        past_participle: ["He ___ la verdad durante años.", "I have known the truth for years."],
    },
    ver: {
        indicative: [
            ["Yo ___ la televisión por las noches.", "I watch television at night."],
            ["Tú ___ muchas películas.", "You watch a lot of movies."],
            ["Él ___ a sus amigos cada semana.", "He sees his friends every week."],
            ["Nosotros ___ el partido juntos.", "We watch the match together."],
            ["Vosotros ___ demasiado la pantalla.", "You all look at screens too much."],
            ["Ellos ___ el amanecer desde la colina.", "They see the sunrise from the hill."],
        ],
        subjunctive: [
            ["Quiero que yo ___ el mundo.", "I want to see the world."],
            ["Espero que tú ___ los resultados.", "I hope you see the results."],
            ["Es bueno que ella ___ a sus amigos.", "It's good that she sees her friends."],
            ["Ojalá que nosotros ___ una solución.", "Hopefully we see a solution."],
            ["Quiero que vosotros ___ la diferencia.", "I want you all to see the difference."],
            ["Espero que ellos ___ el problema.", "I hope they see the problem."],
        ],
        imperative: [
            ["___ lo que te digo.", "See what I'm telling you."],
            ["___ la presentación antes de mañana.", "See the presentation before tomorrow."],
            ["___ la película juntos.", "Let's watch the movie together."],
            ["___ las instrucciones.", "Look at the instructions."],
            ["___ los resultados del estudio.", "See the results of the study."],
        ],
        gerund: ["Estoy ___ algo extraño.", "I am seeing something strange."],
        infinitive: ["Quiero ___ ese espectáculo.", "I want to see that show."],
        past_participle: ["He ___ esa película tres veces.", "I have seen that movie three times."],
    },
    dar: {
        indicative: [
            ["Yo ___ un paseo cada tarde.", "I take a walk every afternoon."],
            ["Tú ___ buenos consejos.", "You give good advice."],
            ["Ella ___ clases de piano.", "She gives piano lessons."],
            ["Nosotros ___ una fiesta el sábado.", "We are having a party on Saturday."],
            ["Vosotros ___ mucho dinero a la caridad.", "You all give a lot of money to charity."],
            ["Ellos ___ las gracias a todos.", "They give thanks to everyone."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más a los demás.", "I want to give more to others."],
            ["Espero que tú ___ tu opinión.", "I hope you give your opinion."],
            ["Es importante que ella ___ una respuesta.", "It's important that she give an answer."],
            ["Ojalá que nosotros ___ lo mejor.", "Hopefully we give our best."],
            ["Necesito que vosotros ___ un informe.", "I need you all to give a report."],
            ["Quiero que ellos ___ más detalles.", "I want them to give more details."],
        ],
        imperative: [
            ["___ una vuelta por el parque.", "Take a walk through the park."],
            ["___ su nombre completo.", "Give your full name."],
            ["___ las gracias a todos.", "Let's thank everyone."],
            ["___ todo lo que podáis.", "Give everything you can."],
            ["___ la información necesaria.", "Give the necessary information."],
        ],
        gerund: ["Está ___ una conferencia ahora.", "He is giving a lecture now."],
        infinitive: ["Hay que ___ más oportunidades.", "One must give more opportunities."],
        past_participle: ["He ___ mi opinión sobre el tema.", "I have given my opinion on the topic."],
    },
    venir: {
        indicative: [
            ["Yo ___ a trabajar en metro.", "I come to work by metro."],
            ["Tú ___ a clase todos los días.", "You come to class every day."],
            ["Ella ___ a visitarnos cada domingo.", "She comes to visit us every Sunday."],
            ["Nosotros ___ de una familia grande.", "We come from a big family."],
            ["Vosotros ___ de España.", "You all come from Spain."],
            ["Ellos ___ tarde a las reuniones.", "They come late to meetings."],
        ],
        subjunctive: [
            ["Quiero que yo ___ antes.", "I want to come earlier."],
            ["Espero que tú ___ a la fiesta.", "I hope you come to the party."],
            ["Es importante que ella ___ a la reunión.", "It's important that she come to the meeting."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we come together."],
            ["Quiero que vosotros ___ con nosotros.", "I want you all to come with us."],
            ["Espero que ellos ___ a tiempo.", "I hope they come on time."],
        ],
        imperative: [
            ["___ aquí, por favor.", "Come here, please."],
            ["___ a mi oficina.", "Come to my office."],
            ["___ todos juntos.", "Let's all come together."],
            ["___ con nosotros.", "Come with us."],
            ["___ a la reunión de mañana.", "Come to tomorrow's meeting."],
        ],
        gerund: ["Está ___ hacia nosotros.", "He is coming towards us."],
        infinitive: ["No puedo ___ hoy.", "I can't come today."],
        past_participle: ["Ha ___ de París esta mañana.", "She has come from Paris this morning."],
    },
    pensar: {
        indicative: [
            ["Yo ___ que es una buena idea.", "I think it's a good idea."],
            ["Tú ___ demasiado en el pasado.", "You think too much about the past."],
            ["Ella ___ ir al extranjero.", "She is thinking about going abroad."],
            ["Nosotros ___ en vosotros mucho.", "We think about you all a lot."],
            ["Vosotros ___ de manera diferente.", "You all think differently."],
            ["Ellos ___ que el proyecto tendrá éxito.", "They think the project will succeed."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más en positivo.", "I want to think more positively."],
            ["Espero que tú ___ en nosotros.", "I hope you think about us."],
            ["Es bueno que ella ___ antes de actuar.", "It's good that she thinks before acting."],
            ["Ojalá que nosotros ___ en soluciones.", "Hopefully we think about solutions."],
            ["Quiero que vosotros ___ bien la decisión.", "I want you all to think the decision through."],
            ["Espero que ellos ___ con lógica.", "I hope they think logically."],
        ],
        imperative: [
            ["___ antes de hablar.", "Think before you speak."],
            ["___ en las consecuencias.", "Think about the consequences."],
            ["___ en positivo.", "Let's think positively."],
            ["___ bien la respuesta.", "Think the answer through carefully."],
            ["___ con calma.", "Think calmly."],
        ],
        gerund: ["Está ___ en cambiar de trabajo.", "He is thinking about changing jobs."],
        infinitive: ["Hay que ___ en el futuro.", "One must think about the future."],
        past_participle: ["He ___ mucho en esta decisión.", "I have thought a lot about this decision."],
    },
    deber: {
        indicative: [
            ["Yo ___ estudiar más.", "I must study more."],
            ["Tú ___ descansar más.", "You must rest more."],
            ["Ella ___ llegar pronto.", "She must arrive soon."],
            ["Nosotros ___ terminar el proyecto.", "We must finish the project."],
            ["Vosotros ___ ser más cuidadosos.", "You all must be more careful."],
            ["Ellos ___ pagar la factura.", "They must pay the bill."],
        ],
        subjunctive: [
            ["Quiero que yo ___ menos.", "I want to owe less."],
            ["Espero que tú ___ tener más cuidado.", "I hope you should be more careful."],
            ["Es importante que ella ___ respeto a todos.", "It's important that she owe respect to everyone."],
            ["Ojalá que nosotros ___ hacer lo correcto.", "Hopefully we should do the right thing."],
            ["Quiero que vosotros ___ cumplir las normas.", "I want you all to have to follow the rules."],
            ["Espero que ellos ___ rendir cuentas.", "I hope they should be accountable."],
        ],
        imperative: [
            ["___ ser más responsable.", "You must be more responsible."],
            ["___ cumplir con sus obligaciones.", "You must fulfill your obligations."],
            ["___ hacer las cosas bien.", "We must do things well."],
            ["___ respetar las reglas.", "You all must respect the rules."],
            ["___ llegar a tiempo.", "You must arrive on time."],
        ],
        gerund: ["Está ___ mucho dinero al banco.", "He owes a lot of money to the bank."],
        infinitive: ["No se ___ llegar tarde.", "One shouldn't arrive late."],
        past_participle: ["He ___ trabajar mucho esta semana.", "I have had to work a lot this week."],
    },
    escribir: {
        indicative: [
            ["Yo ___ una carta a mi abuela.", "I write a letter to my grandmother."],
            ["Tú ___ muy bien en español.", "You write very well in Spanish."],
            ["Ella ___ novelas en su tiempo libre.", "She writes novels in her free time."],
            ["Nosotros ___ el informe juntos.", "We write the report together."],
            ["Vosotros ___ muchos correos cada día.", "You all write many emails every day."],
            ["Ellos ___ artículos para una revista.", "They write articles for a magazine."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejor.", "I want to write better."],
            ["Espero que tú ___ pronto.", "I hope you write soon."],
            ["Es importante que ella ___ el informe.", "It's important that she write the report."],
            ["Ojalá que nosotros ___ algo juntos.", "Hopefully we write something together."],
            ["Necesito que vosotros ___ el resumen.", "I need you all to write the summary."],
            ["Quiero que ellos ___ sus ideas.", "I want them to write their ideas."],
        ],
        imperative: [
            ["___ tu nombre aquí.", "Write your name here."],
            ["___ la respuesta en papel.", "Write the answer on paper."],
            ["___ nuestras ideas en la pizarra.", "Let's write our ideas on the board."],
            ["___ vuestros comentarios.", "Write your comments."],
            ["___ sus datos en el formulario.", "Write your details on the form."],
        ],
        gerund: ["Está ___ una novela.", "She is writing a novel."],
        infinitive: ["Necesito ___ una carta de presentación.", "I need to write a cover letter."],
        past_participle: ["Ha ___ tres libros hasta ahora.", "She has written three books so far."],
    },
    leer: {
        indicative: [
            ["Yo ___ un libro cada mes.", "I read a book every month."],
            ["Tú ___ el periódico cada mañana.", "You read the newspaper every morning."],
            ["Ella ___ novelas de ciencia ficción.", "She reads science fiction novels."],
            ["Nosotros ___ mucho en verano.", "We read a lot in summer."],
            ["Vosotros ___ las instrucciones antes de empezar.", "You all read the instructions before starting."],
            ["Ellos ___ el contrato cuidadosamente.", "They read the contract carefully."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más.", "I want to read more."],
            ["Espero que tú ___ el documento.", "I hope you read the document."],
            ["Es importante que ella ___ el contrato.", "It's important that she read the contract."],
            ["Ojalá que nosotros ___ más libros.", "Hopefully we read more books."],
            ["Quiero que vosotros ___ el informe.", "I want you all to read the report."],
            ["Espero que ellos ___ las instrucciones.", "I hope they read the instructions."],
        ],
        imperative: [
            ["___ el capítulo para mañana.", "Read the chapter for tomorrow."],
            ["___ el contrato antes de firmar.", "Read the contract before signing."],
            ["___ el artículo juntos.", "Let's read the article together."],
            ["___ en voz alta.", "Read aloud."],
            ["___ las instrucciones con cuidado.", "Read the instructions carefully."],
        ],
        gerund: ["Está ___ un artículo interesante.", "He is reading an interesting article."],
        infinitive: ["Me gusta ___ antes de dormir.", "I like to read before sleeping."],
        past_participle: ["He ___ ese libro dos veces.", "I have read that book twice."],
    },
    poner: {
        indicative: [
            ["Yo ___ la mesa para cenar.", "I set the table for dinner."],
            ["Tú ___ mucho esfuerzo en tu trabajo.", "You put a lot of effort into your work."],
            ["Ella ___ la ropa en el armario.", "She puts the clothes in the wardrobe."],
            ["Nosotros ___ la música muy alta.", "We put the music on very loud."],
            ["Vosotros ___ todo en orden.", "You all put everything in order."],
            ["Ellos ___ las maletas en el coche.", "They put the suitcases in the car."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más atención.", "I want to pay more attention."],
            ["Espero que tú ___ más esfuerzo.", "I hope you put in more effort."],
            ["Es importante que ella ___ todo en orden.", "It's important that she put everything in order."],
            ["Ojalá que nosotros ___ más cuidado.", "Hopefully we are more careful."],
            ["Necesito que vosotros ___ las sillas.", "I need you all to put the chairs out."],
            ["Quiero que ellos ___ más empeño.", "I want them to put in more effort."],
        ],
        imperative: [
            ["___ la mesa, por favor.", "Set the table, please."],
            ["___ el libro en la estantería.", "Put the book on the shelf."],
            ["___ todo en su lugar.", "Let's put everything in its place."],
            ["___ las cosas en la mochila.", "Put your things in the backpack."],
            ["___ los documentos sobre la mesa.", "Put the documents on the table."],
        ],
        gerund: ["Está ___ los platos en la mesa.", "She is putting the plates on the table."],
        infinitive: ["Hay que ___ más atención en clase.", "One must pay more attention in class."],
        past_participle: ["He ___ el abrigo en el armario.", "I have put the coat in the wardrobe."],
    },
    salir: {
        indicative: [
            ["Yo ___ de casa a las ocho.", "I leave home at eight."],
            ["Tú ___ con tus amigos los fines de semana.", "You go out with your friends on weekends."],
            ["Ella ___ del trabajo tarde.", "She leaves work late."],
            ["Nosotros ___ a cenar esta noche.", "We are going out to dinner tonight."],
            ["Vosotros ___ muy temprano.", "You all leave very early."],
            ["Ellos ___ en el próximo tren.", "They leave on the next train."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más a menudo.", "I want to go out more often."],
            ["Espero que tú ___ bien en el examen.", "I hope you do well on the exam."],
            ["Es importante que ella ___ a tiempo.", "It's important that she leave on time."],
            ["Ojalá que nosotros ___ todos juntos.", "Hopefully we all go out together."],
            ["Quiero que vosotros ___ antes de las diez.", "I want you all to leave before ten."],
            ["Espero que ellos ___ con buen tiempo.", "I hope they leave in good weather."],
        ],
        imperative: [
            ["___ de aquí ahora mismo.", "Leave here right now."],
            ["___ por la puerta trasera.", "Go out through the back door."],
            ["___ a tomar el aire.", "Let's go outside for fresh air."],
            ["___ antes de que llueva.", "Leave before it rains."],
            ["___ en grupos de dos.", "Leave in groups of two."],
        ],
        gerund: ["Está ___ del edificio.", "He is leaving the building."],
        infinitive: ["Quiero ___ a pasear.", "I want to go out for a walk."],
        past_participle: ["Ha ___ muy temprano esta mañana.", "She has left very early this morning."],
    },
    conocer: {
        indicative: [
            ["Yo ___ muy bien la ciudad.", "I know the city very well."],
            ["Tú ___ a mucha gente interesante.", "You know a lot of interesting people."],
            ["Él ___ al director personalmente.", "He knows the director personally."],
            ["Nosotros ___ ese restaurante.", "We know that restaurant."],
            ["Vosotros ___ a todos en el barrio.", "You all know everyone in the neighborhood."],
            ["Ellos ___ bien la cultura española.", "They know Spanish culture well."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más gente.", "I want to meet more people."],
            ["Espero que tú ___ a alguien especial.", "I hope you meet someone special."],
            ["Es bueno que ella ___ la cultura.", "It's good that she knows the culture."],
            ["Ojalá que nosotros ___ la solución.", "Hopefully we know the solution."],
            ["Quiero que vosotros ___ al nuevo jefe.", "I want you all to meet the new boss."],
            ["Espero que ellos ___ nuestro trabajo.", "I hope they know our work."],
        ],
        imperative: [
            ["___ al nuevo compañero.", "Meet the new colleague."],
            ["___ los detalles del proyecto.", "Get to know the project details."],
            ["___ mejor nuestra ciudad.", "Let's get to know our city better."],
            ["___ al resto del equipo.", "Meet the rest of the team."],
            ["___ todos los procedimientos.", "Learn all the procedures."],
        ],
        gerund: ["Está ___ a sus nuevos vecinos.", "She is getting to know her new neighbors."],
        infinitive: ["Quiero ___ más sobre la historia.", "I want to know more about history."],
        past_participle: ["He ___ a personas increíbles aquí.", "I have met incredible people here."],
    },
    trabajar: {
        indicative: [
            ["Yo ___ en una empresa de tecnología.", "I work at a technology company."],
            ["Tú ___ demasiadas horas.", "You work too many hours."],
            ["Ella ___ desde casa los viernes.", "She works from home on Fridays."],
            ["Nosotros ___ bien en equipo.", "We work well as a team."],
            ["Vosotros ___ en el mismo departamento.", "You all work in the same department."],
            ["Ellos ___ en un proyecto importante.", "They work on an important project."],
        ],
        subjunctive: [
            ["Quiero que yo ___ en algo que me guste.", "I want to work on something I like."],
            ["Espero que tú ___ con nosotros.", "I hope you work with us."],
            ["Es importante que ella ___ con dedicación.", "It's important that she work with dedication."],
            ["Ojalá que nosotros ___ bien juntos.", "Hopefully we work well together."],
            ["Necesito que vosotros ___ más rápido.", "I need you all to work faster."],
            ["Quiero que ellos ___ en equipo.", "I want them to work as a team."],
        ],
        imperative: [
            ["___ con más cuidado.", "Work more carefully."],
            ["___ en ese proyecto primero.", "Work on that project first."],
            ["___ juntos en esto.", "Let's work together on this."],
            ["___ en silencio.", "Work in silence."],
            ["___ con eficiencia.", "Work efficiently."],
        ],
        gerund: ["Está ___ en un proyecto nuevo.", "He is working on a new project."],
        infinitive: ["Hay que ___ duro para tener éxito.", "One must work hard to succeed."],
        past_participle: ["He ___ todo el fin de semana.", "I have worked all weekend."],
    },
    necesitar: {
        indicative: [
            ["Yo ___ más tiempo para terminar.", "I need more time to finish."],
            ["Tú ___ descansar.", "You need to rest."],
            ["Ella ___ ayuda con el proyecto.", "She needs help with the project."],
            ["Nosotros ___ más información.", "We need more information."],
            ["Vosotros ___ una pausa.", "You all need a break."],
            ["Ellos ___ dinero para el viaje.", "They need money for the trip."],
        ],
        subjunctive: [
            ["Ojalá que yo ___ menos ayuda.", "Hopefully I need less help."],
            ["Espero que tú ___ algo de mí.", "I hope you need something from me."],
            ["Es importante que ella ___ apoyo.", "It's important that she get the support she needs."],
            ["Ojalá que nosotros ___ solo tiempo.", "Hopefully we only need time."],
            ["Quiero que vosotros ___ menos recursos.", "I want you all to need fewer resources."],
            ["Espero que ellos ___ nuestra ayuda.", "I hope they need our help."],
        ],
        imperative: [
            ["___ menos cosas materiales.", "Need fewer material things."],
            ["___ pedir ayuda cuando sea necesario.", "Feel free to ask for help when needed."],
            ["___ menos y dar más.", "Let's need less and give more."],
            ["___ ser más independientes.", "Be more independent."],
            ["___ preguntar si tienen dudas.", "Feel free to ask if you have questions."],
        ],
        gerund: ["Está ___ más espacio.", "She is needing more space."],
        infinitive: ["No quiero ___ ayuda.", "I don't want to need help."],
        past_participle: ["He ___ mucha paciencia hoy.", "I have needed a lot of patience today."],
    },
    sentir: {
        indicative: [
            ["Yo ___ mucho frío en invierno.", "I feel very cold in winter."],
            ["Tú ___ mucha presión en el trabajo.", "You feel a lot of pressure at work."],
            ["Ella ___ nostalgia por su país.", "She feels nostalgia for her country."],
            ["Nosotros ___ que todo va bien.", "We feel that everything is going well."],
            ["Vosotros ___ el calor del verano.", "You all feel the summer heat."],
            ["Ellos ___ orgullo por su equipo.", "They feel pride for their team."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más seguro.", "I want to feel more secure."],
            ["Espero que tú ___ mejor pronto.", "I hope you feel better soon."],
            ["Es importante que ella ___ apoyada.", "It's important that she feel supported."],
            ["Ojalá que nosotros ___ más unidos.", "Hopefully we feel more united."],
            ["Quiero que vosotros ___ cómodos.", "I want you all to feel comfortable."],
            ["Espero que ellos ___ bienvenidos.", "I hope they feel welcome."],
        ],
        imperative: [
            ["___ la música.", "Feel the music."],
            ["___ la diferencia.", "Feel the difference."],
            ["___ el momento presente.", "Let's feel the present moment."],
            ["___ libres de expresaros.", "Feel free to express yourselves."],
            ["___ bienvenidos.", "Feel welcome."],
        ],
        gerund: ["Está ___ mejor después del descanso.", "He is feeling better after the rest."],
        infinitive: ["Es normal ___ nervioso antes de hablar.", "It's normal to feel nervous before speaking."],
        past_participle: ["He ___ mucha alegría hoy.", "I have felt a lot of joy today."],
    },
    dormir: {
        indicative: [
            ["Yo ___ ocho horas cada noche.", "I sleep eight hours every night."],
            ["Tú ___ muy poco entre semana.", "You sleep very little during the week."],
            ["Él ___ la siesta después de comer.", "He sleeps a nap after eating."],
            ["Nosotros ___ en tiendas de campaña.", "We sleep in tents."],
            ["Vosotros ___ hasta muy tarde.", "You all sleep until very late."],
            ["Ellos ___ profundamente.", "They sleep deeply."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejor.", "I want to sleep better."],
            ["Espero que tú ___ bien esta noche.", "I hope you sleep well tonight."],
            ["Es importante que ella ___ suficiente.", "It's important that she sleep enough."],
            ["Ojalá que nosotros ___ tranquilos.", "Hopefully we sleep peacefully."],
            ["Quiero que vosotros ___ pronto.", "I want you all to go to sleep soon."],
            ["Espero que ellos ___ bien.", "I hope they sleep well."],
        ],
        imperative: [
            ["___ un poco antes del viaje.", "Sleep a little before the trip."],
            ["___ ocho horas mínimo.", "Sleep at least eight hours."],
            ["___ la siesta juntos.", "Let's take a nap together."],
            ["___ pronto, que mañana madrugaremos.", "Go to sleep early, we'll get up early tomorrow."],
            ["___ bien esta noche.", "Sleep well tonight."],
        ],
        gerund: ["Está ___ en el sofá.", "He is sleeping on the sofa."],
        infinitive: ["Necesito ___ más.", "I need to sleep more."],
        past_participle: ["He ___ solo cuatro horas.", "I have slept only four hours."],
    },
    encontrar: {
        indicative: [
            ["Yo ___ trabajo fácilmente.", "I find work easily."],
            ["Tú ___ siempre las llaves.", "You always find the keys."],
            ["Ella ___ muchas dificultades.", "She encounters many difficulties."],
            ["Nosotros ___ la solución juntos.", "We find the solution together."],
            ["Vosotros ___ algo que os guste.", "You all find something you like."],
            ["Ellos ___ la oficina con dificultad.", "They find the office with difficulty."],
        ],
        subjunctive: [
            ["Quiero que yo ___ una buena oportunidad.", "I want to find a good opportunity."],
            ["Espero que tú ___ lo que buscas.", "I hope you find what you're looking for."],
            ["Es bueno que ella ___ apoyo.", "It's good that she finds support."],
            ["Ojalá que nosotros ___ la respuesta.", "Hopefully we find the answer."],
            ["Quiero que vosotros ___ el camino.", "I want you all to find the way."],
            ["Espero que ellos ___ trabajo.", "I hope they find work."],
        ],
        imperative: [
            ["___ una solución para este problema.", "Find a solution to this problem."],
            ["___ los documentos necesarios.", "Find the necessary documents."],
            ["___ un punto en común.", "Let's find common ground."],
            ["___ la respuesta antes del lunes.", "Find the answer before Monday."],
            ["___ la mejor opción.", "Find the best option."],
        ],
        gerund: ["Está ___ la información en internet.", "She is finding information on the internet."],
        infinitive: ["Es difícil ___ tiempo para todo.", "It's difficult to find time for everything."],
        past_participle: ["He ___ las llaves al fin.", "I have finally found the keys."],
    },
    pedir: {
        indicative: [
            ["Yo ___ ayuda cuando la necesito.", "I ask for help when I need it."],
            ["Tú ___ siempre permiso.", "You always ask for permission."],
            ["Ella ___ el menú al camarero.", "She asks the waiter for the menu."],
            ["Nosotros ___ una mesa para cuatro.", "We ask for a table for four."],
            ["Vosotros ___ demasiado.", "You all ask for too much."],
            ["Ellos ___ información sobre el curso.", "They ask for information about the course."],
        ],
        subjunctive: [
            ["Quiero que yo ___ las cosas con educación.", "I want to ask for things politely."],
            ["Espero que tú ___ disculpas.", "I hope you ask for an apology."],
            ["Es importante que ella ___ ayuda.", "It's important that she ask for help."],
            ["Ojalá que nosotros ___ lo correcto.", "Hopefully we ask for the right thing."],
            ["Necesito que vosotros ___ más tiempo.", "I need you all to ask for more time."],
            ["Quiero que ellos ___ las instrucciones.", "I want them to ask for the instructions."],
        ],
        imperative: [
            ["___ la cuenta, por favor.", "Ask for the bill, please."],
            ["___ una cita con el médico.", "Ask for an appointment with the doctor."],
            ["___ más información si la necesitamos.", "Let's ask for more information if we need it."],
            ["___ disculpas cuando os equivoquéis.", "Ask for forgiveness when you make mistakes."],
            ["___ ayuda si la necesitan.", "Ask for help if they need it."],
        ],
        gerund: ["Está ___ ayuda al profesor.", "He is asking the teacher for help."],
        infinitive: ["No me gusta ___ favores.", "I don't like asking for favors."],
        past_participle: ["He ___ la cuenta ya.", "I have already asked for the bill."],
    },
    abrir: {
        indicative: [
            ["Yo ___ la ventana cada mañana.", "I open the window every morning."],
            ["Tú ___ la puerta para todos.", "You open the door for everyone."],
            ["Él ___ su tienda a las nueve.", "He opens his shop at nine."],
            ["Nosotros ___ la reunión con una pregunta.", "We open the meeting with a question."],
            ["Vosotros ___ las cajas con cuidado.", "You all open the boxes carefully."],
            ["Ellos ___ el museo los domingos.", "They open the museum on Sundays."],
        ],
        subjunctive: [
            ["Quiero que yo ___ nuevas posibilidades.", "I want to open new possibilities."],
            ["Espero que tú ___ la puerta.", "I hope you open the door."],
            ["Es importante que ella ___ el negocio a tiempo.", "It's important that she open the business on time."],
            ["Ojalá que nosotros ___ un camino juntos.", "Hopefully we open a path together."],
            ["Necesito que vosotros ___ la sala.", "I need you all to open the room."],
            ["Quiero que ellos ___ las posibilidades.", "I want them to open up the possibilities."],
        ],
        imperative: [
            ["___ la ventana, hace calor.", "Open the window, it's hot."],
            ["___ la puerta, por favor.", "Open the door, please."],
            ["___ la mente a nuevas ideas.", "Let's open our minds to new ideas."],
            ["___ los libros en la página diez.", "Open your books to page ten."],
            ["___ los paquetes con cuidado.", "Open the packages carefully."],
        ],
        gerund: ["Está ___ las cajas del almacén.", "He is opening the warehouse boxes."],
        infinitive: ["Hay que ___ la mente a nuevas ideas.", "One must open one's mind to new ideas."],
        past_participle: ["He ___ la carta esta mañana.", "I have opened the letter this morning."],
    },
    jugar: {
        indicative: [
            ["Yo ___ al fútbol los sábados.", "I play football on Saturdays."],
            ["Tú ___ muy bien al ajedrez.", "You play chess very well."],
            ["Ella ___ con sus hijos en el parque.", "She plays with her children in the park."],
            ["Nosotros ___ en el mismo equipo.", "We play on the same team."],
            ["Vosotros ___ al tenis juntos.", "You all play tennis together."],
            ["Ellos ___ videojuegos por las tardes.", "They play video games in the afternoons."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejor.", "I want to play better."],
            ["Espero que tú ___ en el partido.", "I hope you play in the match."],
            ["Es importante que ella ___ limpio.", "It's important that she play fair."],
            ["Ojalá que nosotros ___ bien hoy.", "Hopefully we play well today."],
            ["Quiero que vosotros ___ con más ganas.", "I want you all to play with more enthusiasm."],
            ["Espero que ellos ___ bien.", "I hope they play well."],
        ],
        imperative: [
            ["___ limpio siempre.", "Always play fair."],
            ["___ con el equipo.", "Play with the team."],
            ["___ todos juntos.", "Let's all play together."],
            ["___ con más energía.", "Play with more energy."],
            ["___ por diversión.", "Play for fun."],
        ],
        gerund: ["Está ___ con su perro en el jardín.", "He is playing with his dog in the garden."],
        infinitive: ["Me gusta ___ al ajedrez.", "I like playing chess."],
        past_participle: ["He ___ bien hoy.", "I have played well today."],
    },
    entender: {
        indicative: [
            ["Yo ___ muy bien el francés.", "I understand French very well."],
            ["Tú ___ las instrucciones.", "You understand the instructions."],
            ["Él ___ el problema claramente.", "He understands the problem clearly."],
            ["Nosotros ___ lo que nos dices.", "We understand what you tell us."],
            ["Vosotros ___ la situación.", "You all understand the situation."],
            ["Ellos ___ el contrato perfectamente.", "They understand the contract perfectly."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejor la gramática.", "I want to understand grammar better."],
            ["Espero que tú ___ mi posición.", "I hope you understand my position."],
            ["Es importante que ella ___ las instrucciones.", "It's important that she understand the instructions."],
            ["Ojalá que nosotros ___ todo bien.", "Hopefully we understand everything well."],
            ["Necesito que vosotros ___ las reglas.", "I need you all to understand the rules."],
            ["Quiero que ellos ___ el problema.", "I want them to understand the problem."],
        ],
        imperative: [
            ["___ lo que te digo.", "Understand what I'm telling you."],
            ["___ el punto de vista de los demás.", "Understand others' point of view."],
            ["___ la situación antes de actuar.", "Let's understand the situation before acting."],
            ["___ las instrucciones bien.", "Understand the instructions well."],
            ["___ por qué es importante.", "Understand why it is important."],
        ],
        gerund: ["Está ___ poco a poco.", "He is understanding little by little."],
        infinitive: ["Es difícil ___ todo a la primera.", "It's difficult to understand everything the first time."],
        past_participle: ["He ___ lo que me decías.", "I have understood what you were telling me."],
    },
    volver: {
        indicative: [
            ["Yo ___ a casa a las seis.", "I return home at six."],
            ["Tú ___ siempre tarde.", "You always return late."],
            ["Ella ___ de sus vacaciones mañana.", "She returns from her holidays tomorrow."],
            ["Nosotros ___ al mismo lugar.", "We return to the same place."],
            ["Vosotros ___ pronto del viaje.", "You all return from the trip soon."],
            ["Ellos ___ a casa en Navidad.", "They return home at Christmas."],
        ],
        subjunctive: [
            ["Quiero que yo ___ a estudiar.", "I want to go back to studying."],
            ["Espero que tú ___ pronto.", "I hope you return soon."],
            ["Es importante que ella ___ antes de las diez.", "It's important that she return before ten."],
            ["Ojalá que nosotros ___ a vernos.", "Hopefully we see each other again."],
            ["Quiero que vosotros ___ sanos.", "I want you all to return safe."],
            ["Espero que ellos ___ juntos.", "I hope they return together."],
        ],
        imperative: [
            ["___ cuando quieras.", "Return whenever you want."],
            ["___ a la reunión.", "Return to the meeting."],
            ["___ juntos en el mismo vuelo.", "Let's return together on the same flight."],
            ["___ antes del anochecer.", "Return before nightfall."],
            ["___ con los documentos.", "Return with the documents."],
        ],
        gerund: ["Está ___ de su viaje.", "He is returning from his trip."],
        infinitive: ["Quiero ___ a vivir en España.", "I want to go back to living in Spain."],
        past_participle: ["He ___ a mi ciudad natal.", "I have returned to my hometown."],
    },
    seguir: {
        indicative: [
            ["Yo ___ aprendiendo cada día.", "I keep learning every day."],
            ["Tú ___ el mismo camino que antes.", "You follow the same path as before."],
            ["Ella ___ trabajando en el proyecto.", "She continues working on the project."],
            ["Nosotros ___ las instrucciones.", "We follow the instructions."],
            ["Vosotros ___ el camino correcto.", "You all follow the right path."],
            ["Ellos ___ viviendo en el mismo barrio.", "They continue living in the same neighborhood."],
        ],
        subjunctive: [
            ["Quiero que yo ___ progresando.", "I want to keep progressing."],
            ["Espero que tú ___ adelante.", "I hope you continue forward."],
            ["Es importante que ella ___ el protocolo.", "It's important that she follow the protocol."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we continue together."],
            ["Quiero que vosotros ___ trabajando.", "I want you all to keep working."],
            ["Espero que ellos ___ las instrucciones.", "I hope they follow the instructions."],
        ],
        imperative: [
            ["___ recto por esta calle.", "Keep going straight on this street."],
            ["___ las instrucciones al pie de la letra.", "Follow the instructions to the letter."],
            ["___ adelante a pesar de los obstáculos.", "Let's continue forward despite the obstacles."],
            ["___ trabajando duro.", "Keep working hard."],
            ["___ este camino.", "Follow this path."],
        ],
        gerund: ["Está ___ el mapa para llegar.", "He is following the map to get there."],
        infinitive: ["Hay que ___ practicando para mejorar.", "One must keep practicing to improve."],
        past_participle: ["He ___ tus consejos.", "I have followed your advice."],
    },
    dejar: {
        indicative: [
            ["Yo ___ el trabajo a las cinco.", "I leave work at five."],
            ["Tú ___ siempre las cosas en su sitio.", "You always leave things in their place."],
            ["Ella ___ de fumar el año pasado.", "She quit smoking last year."],
            ["Nosotros ___ el coche en el aparcamiento.", "We leave the car in the parking lot."],
            ["Vosotros ___ la puerta abierta.", "You all leave the door open."],
            ["Ellos ___ un mensaje en el contestador.", "They leave a message on the answering machine."],
        ],
        subjunctive: [
            ["Quiero que yo ___ los malos hábitos.", "I want to give up bad habits."],
            ["Espero que tú ___ de fumar.", "I hope you stop smoking."],
            ["Es importante que ella ___ el dinero en el banco.", "It's important that she leave the money in the bank."],
            ["Ojalá que nosotros ___ todo listo.", "Hopefully we leave everything ready."],
            ["Necesito que vosotros ___ el local limpio.", "I need you all to leave the place clean."],
            ["Quiero que ellos ___ de molestar.", "I want them to stop bothering."],
        ],
        imperative: [
            ["___ eso aquí.", "Leave that here."],
            ["___ su mensaje después de la señal.", "Leave your message after the beep."],
            ["___ las cosas en su lugar.", "Let's leave things in their place."],
            ["___ de discutir.", "Stop arguing."],
            ["___ sus llaves en la recepción.", "Leave your keys at reception."],
        ],
        gerund: ["Está ___ de lado sus problemas.", "He is leaving aside his problems."],
        infinitive: ["No puedo ___ de pensar en ello.", "I can't stop thinking about it."],
        past_participle: ["He ___ el trabajo a tiempo.", "I have left the work on time."],
    },
    tomar: {
        indicative: [
            ["Yo ___ el autobús cada mañana.", "I take the bus every morning."],
            ["Tú ___ café con leche.", "You drink coffee with milk."],
            ["Ella ___ apuntes en clase.", "She takes notes in class."],
            ["Nosotros ___ decisiones juntos.", "We make decisions together."],
            ["Vosotros ___ el tren a Madrid.", "You all take the train to Madrid."],
            ["Ellos ___ un descanso a las tres.", "They take a break at three."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejores decisiones.", "I want to make better decisions."],
            ["Espero que tú ___ la medicina.", "I hope you take the medicine."],
            ["Es importante que ella ___ nota de esto.", "It's important that she take note of this."],
            ["Ojalá que nosotros ___ la decisión correcta.", "Hopefully we make the right decision."],
            ["Necesito que vosotros ___ el tren de las nueve.", "I need you all to take the nine o'clock train."],
            ["Quiero que ellos ___ su tiempo.", "I want them to take their time."],
        ],
        imperative: [
            ["___ asiento, por favor.", "Take a seat, please."],
            ["___ la medicina con agua.", "Take the medicine with water."],
            ["___ un descanso.", "Let's take a break."],
            ["___ nota de esto.", "Take note of this."],
            ["___ sus pasaportes antes de salir.", "Take your passports before leaving."],
        ],
        gerund: ["Está ___ apuntes muy detallados.", "She is taking very detailed notes."],
        infinitive: ["Hay que ___ una decisión hoy.", "One must make a decision today."],
        past_participle: ["He ___ la medicina ya.", "I have already taken the medicine."],
    },
    esperar: {
        indicative: [
            ["Yo ___ el autobús cada día.", "I wait for the bus every day."],
            ["Tú ___ noticias de tu amigo.", "You wait for news from your friend."],
            ["Ella ___ que todo salga bien.", "She hopes everything goes well."],
            ["Nosotros ___ en la sala de espera.", "We wait in the waiting room."],
            ["Vosotros ___ la respuesta del jefe.", "You all wait for the boss's answer."],
            ["Ellos ___ una oportunidad.", "They wait for an opportunity."],
        ],
        subjunctive: [
            ["Quiero que yo ___ con más paciencia.", "I want to wait with more patience."],
            ["Espero que tú ___ hasta que llegue.", "I hope you wait until I arrive."],
            ["Es bueno que ella ___ antes de actuar.", "It's good that she waits before acting."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we wait together."],
            ["Quiero que vosotros ___ aquí.", "I want you all to wait here."],
            ["Espero que ellos ___ la respuesta.", "I hope they wait for the answer."],
        ],
        imperative: [
            ["___ aquí un momento.", "Wait here a moment."],
            ["___ a que llegue el director.", "Wait for the director to arrive."],
            ["___ a que todos estén listos.", "Let's wait until everyone is ready."],
            ["___ fuera de la sala.", "Wait outside the room."],
            ["___ el turno correspondiente.", "Wait for your turn."],
        ],
        gerund: ["Está ___ el resultado del examen.", "She is waiting for the exam result."],
        infinitive: ["Hay que ___ con paciencia.", "One must wait patiently."],
        past_participle: ["He ___ más de una hora.", "I have waited more than an hour."],
    },
    pasar: {
        indicative: [
            ["Yo ___ mucho tiempo en casa.", "I spend a lot of time at home."],
            ["Tú ___ por el parque cada día.", "You pass through the park every day."],
            ["Ella ___ sus vacaciones en la playa.", "She spends her holidays at the beach."],
            ["Nosotros ___ por esa calle.", "We pass by that street."],
            ["Vosotros ___ el fin de semana en el campo.", "You all spend the weekend in the countryside."],
            ["Ellos ___ a buscar a los niños.", "They come to pick up the children."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más tiempo con mi familia.", "I want to spend more time with my family."],
            ["Espero que tú ___ un buen rato.", "I hope you have a good time."],
            ["Es importante que ella ___ por aquí.", "It's important that she come by here."],
            ["Ojalá que nosotros ___ un día agradable.", "Hopefully we have a pleasant day."],
            ["Quiero que vosotros ___ a verme.", "I want you all to come by and see me."],
            ["Espero que ellos ___ bien el fin de semana.", "I hope they have a good weekend."],
        ],
        imperative: [
            ["___ por mi oficina mañana.", "Come by my office tomorrow."],
            ["___ a recoger los documentos.", "Come pick up the documents."],
            ["___ un buen rato juntos.", "Let's have a good time together."],
            ["___ la tarde en casa.", "Spend the afternoon at home."],
            ["___ sus vacaciones aquí.", "Spend your holidays here."],
        ],
        gerund: ["Está ___ el verano en el pueblo.", "He is spending the summer in the village."],
        infinitive: ["Me encanta ___ tiempo en la naturaleza.", "I love spending time in nature."],
        past_participle: ["Ha ___ algo extraño.", "Something strange has happened."],
    },
    llamar: {
        indicative: [
            ["Yo ___ a mi madre cada domingo.", "I call my mother every Sunday."],
            ["Tú ___ a la puerta con fuerza.", "You knock on the door hard."],
            ["Ella ___ a sus amigos por teléfono.", "She calls her friends by phone."],
            ["Nosotros ___ al técnico.", "We call the technician."],
            ["Vosotros ___ a la empresa para quejarse.", "You all call the company to complain."],
            ["Ellos ___ al camarero.", "They call the waiter."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más a mis padres.", "I want to call my parents more."],
            ["Espero que tú ___ pronto.", "I hope you call soon."],
            ["Es importante que ella ___ al médico.", "It's important that she call the doctor."],
            ["Ojalá que nosotros ___ a tiempo.", "Hopefully we call in time."],
            ["Necesito que vosotros ___ antes de venir.", "I need you all to call before coming."],
            ["Quiero que ellos ___ para confirmarlo.", "I want them to call to confirm."],
        ],
        imperative: [
            ["___ a la policía ahora mismo.", "Call the police right now."],
            ["___ antes de venir.", "Call before coming."],
            ["___ a todos para la reunión.", "Let's call everyone for the meeting."],
            ["___ a vuestros padres.", "Call your parents."],
            ["___ al número de emergencias.", "Call the emergency number."],
        ],
        gerund: ["Está ___ a todos los clientes.", "He is calling all the clients."],
        infinitive: ["Tengo que ___ al banco.", "I have to call the bank."],
        past_participle: ["He ___ tres veces sin respuesta.", "I have called three times with no answer."],
    },
    llegar: {
        indicative: [
            ["Yo ___ al trabajo a las ocho.", "I arrive at work at eight."],
            ["Tú ___ siempre puntual.", "You always arrive punctually."],
            ["Ella ___ tarde a las reuniones.", "She arrives late to meetings."],
            ["Nosotros ___ al aeropuerto con tiempo.", "We arrive at the airport with time."],
            ["Vosotros ___ antes que nadie.", "You all arrive before anyone."],
            ["Ellos ___ en el vuelo de las cinco.", "They arrive on the five o'clock flight."],
        ],
        subjunctive: [
            ["Quiero que yo ___ a tiempo.", "I want to arrive on time."],
            ["Espero que tú ___ antes de las tres.", "I hope you arrive before three."],
            ["Es importante que ella ___ pronto.", "It's important that she arrive soon."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we arrive together."],
            ["Quiero que vosotros ___ antes del mediodía.", "I want you all to arrive before noon."],
            ["Espero que ellos ___ sin problemas.", "I hope they arrive without problems."],
        ],
        imperative: [
            ["___ a tiempo a la entrevista.", "Arrive on time to the interview."],
            ["___ antes de las nueve.", "Arrive before nine."],
            ["___ todos juntos.", "Let's arrive all together."],
            ["___ con el material necesario.", "Arrive with the necessary material."],
            ["___ con antelación.", "Arrive in advance."],
        ],
        gerund: ["Está ___ al aeropuerto en este momento.", "She is arriving at the airport right now."],
        infinitive: ["Hay que ___ pronto.", "One must arrive early."],
        past_participle: ["Ha ___ el paquete.", "The package has arrived."],
    },
    empezar: {
        indicative: [
            ["Yo ___ a trabajar a las nueve.", "I start working at nine."],
            ["Tú ___ el proyecto mañana.", "You start the project tomorrow."],
            ["Ella ___ un nuevo curso.", "She starts a new course."],
            ["Nosotros ___ la reunión a tiempo.", "We start the meeting on time."],
            ["Vosotros ___ siempre tarde.", "You all always start late."],
            ["Ellos ___ a construir la casa.", "They start building the house."],
        ],
        subjunctive: [
            ["Quiero que yo ___ un nuevo proyecto.", "I want to start a new project."],
            ["Espero que tú ___ pronto.", "I hope you start soon."],
            ["Es importante que ella ___ sin demora.", "It's important that she start without delay."],
            ["Ojalá que nosotros ___ bien.", "Hopefully we start well."],
            ["Necesito que vosotros ___ ahora.", "I need you all to start now."],
            ["Quiero que ellos ___ a las ocho.", "I want them to start at eight."],
        ],
        imperative: [
            ["___ con los ejercicios.", "Start with the exercises."],
            ["___ desde el principio.", "Start from the beginning."],
            ["___ la reunión.", "Let's start the meeting."],
            ["___ sin mí si llego tarde.", "Start without me if I'm late."],
            ["___ por el primer punto.", "Start with the first point."],
        ],
        gerund: ["Está ___ un nuevo proyecto.", "He is starting a new project."],
        infinitive: ["Hay que ___ en algún momento.", "One must start at some point."],
        past_participle: ["He ___ a entender mejor.", "I have started to understand better."],
    },
    buscar: {
        indicative: [
            ["Yo ___ trabajo en internet.", "I look for work on the internet."],
            ["Tú ___ siempre las llaves.", "You always look for the keys."],
            ["Él ___ información sobre el tema.", "He looks for information about the topic."],
            ["Nosotros ___ una solución al problema.", "We look for a solution to the problem."],
            ["Vosotros ___ un apartamento nuevo.", "You all look for a new apartment."],
            ["Ellos ___ al perro por el barrio.", "They look for the dog around the neighborhood."],
        ],
        subjunctive: [
            ["Quiero que yo ___ mejores opciones.", "I want to look for better options."],
            ["Espero que tú ___ la respuesta.", "I hope you look for the answer."],
            ["Es importante que ella ___ apoyo.", "It's important that she look for support."],
            ["Ojalá que nosotros ___ algo juntos.", "Hopefully we look for something together."],
            ["Necesito que vosotros ___ los documentos.", "I need you all to look for the documents."],
            ["Quiero que ellos ___ una solución.", "I want them to look for a solution."],
        ],
        imperative: [
            ["___ las llaves en el cajón.", "Look for the keys in the drawer."],
            ["___ más información antes de decidir.", "Look for more information before deciding."],
            ["___ una salida.", "Let's look for a way out."],
            ["___ entre vuestras notas.", "Look through your notes."],
            ["___ el archivo en el servidor.", "Look for the file on the server."],
        ],
        gerund: ["Está ___ trabajo en otro país.", "He is looking for work in another country."],
        infinitive: ["Tengo que ___ un hotel para mañana.", "I have to look for a hotel for tomorrow."],
        past_participle: ["He ___ por todas partes.", "I have looked everywhere."],
    },
    creer: {
        indicative: [
            ["Yo ___ que todo tiene solución.", "I believe that everything has a solution."],
            ["Tú ___ en ti mismo.", "You believe in yourself."],
            ["Ella ___ que el proyecto saldrá bien.", "She believes the project will go well."],
            ["Nosotros ___ en la importancia de la educación.", "We believe in the importance of education."],
            ["Vosotros ___ que es posible.", "You all believe it's possible."],
            ["Ellos ___ en el poder del trabajo en equipo.", "They believe in the power of teamwork."],
        ],
        subjunctive: [
            ["Quiero que yo ___ más en mí mismo.", "I want to believe more in myself."],
            ["Espero que tú ___ en el proyecto.", "I hope you believe in the project."],
            ["Es importante que ella ___ en sus posibilidades.", "It's important that she believe in her abilities."],
            ["Ojalá que nosotros ___ juntos.", "Hopefully we believe together."],
            ["Quiero que vosotros ___ en el esfuerzo.", "I want you all to believe in hard work."],
            ["Espero que ellos ___ en nosotros.", "I hope they believe in us."],
        ],
        imperative: [
            ["___ en ti mismo.", "Believe in yourself."],
            ["___ que es posible.", "Believe that it's possible."],
            ["___ en el futuro.", "Let's believe in the future."],
            ["___ en vuestras capacidades.", "Believe in your abilities."],
            ["___ en el trabajo en equipo.", "Believe in teamwork."],
        ],
        gerund: ["Está ___ en el éxito del proyecto.", "He is believing in the success of the project."],
        infinitive: ["Es importante ___ en uno mismo.", "It's important to believe in oneself."],
        past_participle: ["Siempre he ___ en ti.", "I have always believed in you."],
    },
    comprar: {
        indicative: [
            ["Yo ___ la compra cada sábado.", "I do the grocery shopping every Saturday."],
            ["Tú ___ ropa nueva cada temporada.", "You buy new clothes every season."],
            ["Ella ___ frutas en el mercado.", "She buys fruit at the market."],
            ["Nosotros ___ los billetes con antelación.", "We buy the tickets in advance."],
            ["Vosotros ___ demasiadas cosas.", "You all buy too many things."],
            ["Ellos ___ una casa nueva.", "They buy a new house."],
        ],
        subjunctive: [
            ["Quiero que yo ___ algo especial.", "I want to buy something special."],
            ["Espero que tú ___ las entradas.", "I hope you buy the tickets."],
            ["Es importante que ella ___ los ingredientes.", "It's important that she buy the ingredients."],
            ["Ojalá que nosotros ___ el piso.", "Hopefully we buy the flat."],
            ["Necesito que vosotros ___ más comida.", "I need you all to buy more food."],
            ["Quiero que ellos ___ los materiales.", "I want them to buy the materials."],
        ],
        imperative: [
            ["___ pan de camino a casa.", "Buy bread on the way home."],
            ["___ los billetes con tiempo.", "Buy the tickets with time to spare."],
            ["___ algo para la cena.", "Let's buy something for dinner."],
            ["___ lo que necesitéis.", "Buy what you need."],
            ["___ los materiales en esa tienda.", "Buy the materials at that store."],
        ],
        gerund: ["Está ___ entradas para el concierto.", "She is buying tickets for the concert."],
        infinitive: ["Necesito ___ un regalo para mi madre.", "I need to buy a gift for my mother."],
        past_participle: ["He ___ todo lo que necesitaba.", "I have bought everything I needed."],
    },
};
